### ISSUE TITLE
Implementation of match() step

### ISSUE THREAD

**Issue by oco-adam** [debug-ito/greskell#10]
Apologies if I'm missing something, but I can't find [the match() step for Graph Traversal](https://tinkerpop.apache.org/docs/current/reference/#match-step).

This would provide a declarative way of traversing the graph, which is extremely useful.

Would it be possible to add this to the API?

**Comment by debug-ito** [comment]
Thanks for reporting.

Sorry, current version of greskell doesn't implement `match` step. I don't have much time to develop it immediately. Pull-requests are welcome.

**Comment by debug-ito** [comment]
[greskell-1.2.0.0](https://hackage.haskell.org/package/greskell-1.2.0.0) now supports match() and where() steps.
