### ISSUE TITLE
Indexing a graph in Gremlin Server

### ISSUE THREAD

**Issue by JeffreyBenjaminBrown** [debug-ito/greskell#3]
I want to manipulate a graph hosted by Gremlin Server. Greskell will let me do most things, and I've gotten to [hello world](https://github.com/JeffreyBenjaminBrown/haskerpop) with it, so to speak -- when I start Gremlin Server in a Docker container, I can interact with it from GHCI. (The [README](https://github.com/JeffreyBenjaminBrown/haskerpop/tree/master/README.md) lists the steps I take to do that.)

Greskell, however, seems to provide no indexing facilities. (Nor does Gremlin itself provide abstractions for indexing, but Gremlin does provides plugins for specific implementations, e.g. Neo4j.)

If I've got a graph hosted by Gremlin Server, and I want to use Greskell (at least most of the time) to manipulate it, is there a way to index certain properties?

Hackage offers [hasbolt](https://hackage.haskell.org/package/hasbolt) for manipulating neo4j graphs directly. If I were to use that, I would have to somehow tell Gremlin Server to use Neo4j (I don't know what it uses by default), and then point hasbolt at Gremlin Server, which for all I know doesn't even make sense.

(This might be TMI, but I tried to make a custom Docker image for Gremlin Server that includes a few neo4j config files borrowed from another project. The [result](https://github.com/JeffreyBenjaminBrown/haskerpop/tree/master/docker-3) ought to be launchable via `/opt/gremlin-server/bin/gremlin-server.sh /mnt/config/gremlin-server.yaml`, but when I do that I get parse errors.)

**Comment by JeffreyBenjaminBrown** [comment]
I just found some neo4j scripts in the Docker image for Grmelin Server. I'll see if I can get this working tonight after work.

**Comment by debug-ito** [comment]
Thanks for bringing this topic.

I've decided that it is out of scope of Greskell to make indexes in the graph database. This is because Tinkerpop Gremlin provides no standardized way to configure indexes (as far as I know), as you already pointed out. Because Greskell is a binding of Gremlin, Greskell does not have that feature either.

**Comment by JeffreyBenjaminBrown** [comment]
I am led to believe, largely by Joshua Shinavier (one of Tinkerpop's authors), that indexing can be made automatic by setting up a neo4j.properties file. The file neo4j-empty.properties can be found in a few places, notably in the Docker image for gremlin-server (in /opt/gremlin/conf). It doesn't show how to specify what to index on, but Josh thinks it'll index stuff as long as auto_indexing=true, even if you don't specify which indexes to make. I'm guessing that under those conditions it'll make all the single-key indices possible and no others.

I'm in the middle of figuring out how to enable the format_migration and store_upgrade options, which are not part of the default .properties file. My efforts, in case they are of interest to future readers of this issue, can be found [here](https://github.com/JeffreyBenjaminBrown/haskerpop/tree/master/docker). (Alternatively, here's a permanent link to [the latest commit](https://github.com/JeffreyBenjaminBrown/haskerpop/tree/154e178d6e4deecc81131a4e55d33d10c5308b2c/docker) of that work, but it's likely to improve in the near future.)

**Comment by JeffreyBenjaminBrown** [comment]
Joshua Shinavier thinks TinkerPop 4 should be out before the end of the year, and says it will have native support for indexing.
