### ISSUE TITLE
Missing steps? `loop`, `loops`, `it`, `object` and `path`.

### ISSUE THREAD

**Issue by JeffreyBenjaminBrown** [debug-ito/greskell#8]
I found an [email thread](https://groups.google.com/d/msg/neo4j/hl2ssBKsvnc/l0HXhHpHDzUJ) on bidirectional search, in which Marko Rodriguez offers two implementations:

```groovy
g.v(1).outE.inV.loop(2){it.object != g.v(2)}.retain([g.v(2)]).path

g.v(1).outE.inV.loop(2){isSimple(it.path) & it.object != g.v(2) & it.loops < 4}.retain([g.v(2)]).path
```

(He provides the second because the first "traversal is scary cause you could have infinite loops and reverberating paths.")

They contain some steps I'm unable to find in Greskell. `retain` appears to be a synonym for `filter`, and `!=` I believe is the same as `.neq`. But I see no equivalent for `loop`, `loops`, `it`, `object` or `path`.

`loop` in particular appears to be important, as [it permits recursion](https://github.com/tinkerpop/gremlin/wiki/Loop-Pattern).

**Comment by debug-ito** [comment]
Yes, `loop` step is not implemented in greskell yet.

I'll try to design API for that, but it may be difficult or not so clean. It may take time to finish, too. I welcome pull-request.

**Comment by debug-ito** [comment]
BTW, `it`, `object`, `loops` are not steps.

**Comment by debug-ito** [comment]
`loop` step is obsolete, I think. Tinkerpop 3.x does not have that. We should use `repeat` instead.

**Comment by debug-ito** [comment]
Sorry, there IS `loops` step since TinkerPop 3.2.5

**Comment by debug-ito** [comment]
- greskell-1.0.1.0 now supports `repeat` and `loops` steps.
- greskell-1.1.0.0 now supports `path` step.
